# Generated by Django 4.0.3 on 2022-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_movie_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='test',
            field=models.JSONField(default=None),
        ),
    ]
