# Generated by Django 4.0.3 on 2022-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_movie_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='test',
        ),
    ]
